name: Daily

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - main
      - master

env:
  PROJECTNAME: casimg

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set build info
        run: |
          echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date +"%a %b %d, %Y at %H:%M:%S %Z")" >> $GITHUB_ENV

      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          LDFLAGS="-s -w -X 'main.Version=${{ env.VERSION }}' -X 'main.CommitID=${{ env.COMMIT_ID }}' -X 'main.BuildDate=${{ env.BUILD_DATE }}'"
          go build -ldflags "${LDFLAGS}" -o ${{ env.PROJECTNAME }} ./src

      - name: Test
        run: |
          go test -v ./...
